# Generated by Django 3.2 on 2022-05-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeintegrents',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
