# Generated by Django 3.2 on 2022-05-28 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20220526_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('ml', 'mililitr'), ('l', 'litr')], max_length=2)),
            ],
        ),
        migrations.RenameModel(
            old_name='IntegrentType',
            new_name='IngredientType',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='integrents',
        ),
        migrations.RenameModel(
            old_name='Integrent',
            new_name='Ingredient',
        ),
        migrations.DeleteModel(
            name='RecipeIntegrents',
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_to_recipe', to='recipe.ingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_to_ingredient', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipe.RecipeIngredients', to='recipe.Ingredient'),
        ),
    ]
