# Generated by Django 3.2 on 2022-08-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20220803_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('unapproved', 'Unapproved'), ('hidden', 'Hidden')], default='unapproved', max_length=10),
        ),
    ]
