# Generated by Django 3.2 on 2022-08-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='recipe.RecipeIngredients', to='recipe.Ingredient'),
        ),
    ]
