# Generated by Django 3.2 on 2022-08-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('unapproved', 'Unapproved'), ('hidden', 'Hidden')], default='unapproved', editable=False, max_length=10),
        ),
    ]
