# Generated by Django 3.2 on 2022-08-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_alter_recipe_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='amount',
            new_name='quantity',
        ),
    ]
