# Generated by Django 3.2 on 2022-09-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_auto_20220918_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipe/img/default.png', upload_to='recipe/img/%Y/%m/%d'),
        ),
    ]
